[theme]
base="light"
primaryColor="#4b71ff"
secondaryBackgroundColor="#ffffff"
font="serif"
[global]
developmentMode = false  # Optional, ensures production settings

[browser]
gatherUsageStats = false  # Disables Streamlit's telemetry

[theme]
primaryColor = "#F63366"  # You can change this to match your branding

[client]
showSidebarNavigation = false  # Hides the top-left hamburger menu

[ui]
hideTopBar = true  # Hides the "Made with Streamlit" footer





