[global]
developmentMode = false  # Optional, ensures production settings

[browser]
gatherUsageStats = false  # Disables Streamlit's telemetry

[client]
showSidebarNavigation = false  # Hides the top-left hamburger menu

[theme]
base = "light"
primaryColor = "#4b71ff"
secondaryBackgroundColor = "#ffffff"
font = "serif"

[ui]
hideTopBar = true  # Hides the "Made with Streamlit" footer
